# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      platform: ubuntu-latest
      account: 234234234
      region: us-east-1
    steps:
      - name: test message
        run: echo Hello, world!

      - name: show environment variables
        run: |
          echo "Platform: $platform"
          echo "Account: $account"
          echo "Region: $region"
